development:
  adapter: postgresql
  encoding: unicode
  database: shoes_shop_development
  pool: 5
  host: localhost
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: shoes_shop_test 
  pool: 5
  username: postgres
  password: postgres

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
