source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

gem 'rails', '~> 6.1.6'
gem 'puma', '~> 5.0'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'

gem 'bootstrap-sass', '~> 3.4.1'
gem 'sassc-rails', '>= 2.1.0'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'oj'
gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'

gem 'meta-tags'
gem "breadcrumbs_on_rails"
gem 'ancestry'

gem 'uglifier'
gem 'activestorage'

group :development, :test do

  gem 'pg'
  gem 'database_cleaner-active_record'
  gem 'database_cleaner-redis'
  gem 'factory_bot'
  gem 'pry', '~> 0.13.1'
  gem 'rails-controller-testing'
  gem 'rb-readline'
  gem 'rspec-json_expectations'

  gem 'rspec-rails'
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  gem 'spring'
end

group :test do

  gem 'capybara', '>= 3.26'
  gem 'webdrivers'

  gem 'db-query-matchers'
  gem 'rubocop', require: false
  gem 'shoulda-matchers', '~> 5.0'

  gem 'json_spec'
  gem 'launchy'

end


gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
