default:      &default
  adapter:    postgresql
  pool:       <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:    5000
  # username:   postgres
  # password:   postgres

development:
  <<:         *default
  database:   shoes_shop

test:
  <<:         *default
  database:   shoes_shop_test

production:
  <<:         *default
  database:   shoes_shop
